Add reload command, config update, change config on damage listener
MagicCheese1/Damage-Indicator pull request #5
Opened 2021-08-09 09:51 UTC by dhannyjsb

2021-08-09 11:06 UTC, MagicCheese1 requested changes
minor changes

2021-08-09 11:06 UTC, MagicCheese1 commented on pom.xml
> +      <groupId>org.spigotmc</groupId>
Please keep paper for now so it works with the current github workflow

2021-08-09 13:14 UTC, dhannyjsb commented on pom.xml
> +      <groupId>org.spigotmc</groupId>
Okay. I've changed it

2021-08-09 13:15 UTC, dhannyjsb commented on src/main/java/com/github/magiccheese1/damageindicator/BukkitEventListener.java
> +                ChatColor.translateAlternateColorCodes('&', Objects.requireNonNull(this.plugin.getConfig().getString(Utility.FORMAT_INDICATOR))));
Sure, can you check new commit.

2021-08-09 13:16 UTC, dhannyjsb commented on src/main/java/com/github/magiccheese1/damageindicator/Cmd.java
> +public class Cmd implements CommandExecutor {
I've changed this class name.

2021-08-09 13:54 UTC, MagicCheese1 commented
When i build it and try to run it, I get a noClassDefFoundError for ConfigUpdater. Am I doing something wrong? Have you even tested this?

2021-08-09 15:01 UTC, dhannyjsb commented
> 
> 
> When i build it and try to run it, I get a noClassDefFoundError for ConfigUpdater. Am I doing something wrong? Have you even tested this?

yes, I have test before pull, ConfigUpdater shade from https://github.com/tchristofferson/Config-Updater

2021-08-09 15:21 UTC, lynxplay commented on src/main/java/com/github/magiccheese1/damageindicator/Main.java
> +            ConfigUpdater.update(this, "config.yml", configFile, Arrays.asList("..."));
What is `"..."` supposed to do here ?

2021-08-09 15:34 UTC, dhannyjsb commented on src/main/java/com/github/magiccheese1/damageindicator/Main.java
> +            ConfigUpdater.update(this, "config.yml", configFile, Arrays.asList("..."));
`"..."` indicate there's no array on config.yml

2021-08-09 16:49 UTC, lynxplay commented on src/main/java/com/github/magiccheese1/damageindicator/Main.java
> +            ConfigUpdater.update(this, "config.yml", configFile, Arrays.asList("..."));
If I understand the ConfigUpdater correctly this argument ([see here](https://github.com/tchristofferson/Config-Updater/blob/master/src/main/java/com/tchristofferson/configupdater/ConfigUpdater.java#L33)) represents the ignore sections that will not be updated.

If you want to indicate that no section should have this treatment, an empty list using [Collections.emptyList()](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Collections.html#emptyList()) might be a better solution.

2021-08-09 23:00 UTC, dhannyjsb commented on src/main/java/com/github/magiccheese1/damageindicator/Main.java
> +            ConfigUpdater.update(this, "config.yml", configFile, Arrays.asList("..."));
Sure. thank you for your solution.

2021-08-10 13:18 UTC, MagicCheese1 commented
> > When i build it and try to run it, I get a noClassDefFoundError for ConfigUpdater. Am I doing something wrong? Have you even tested this?
> 
> yes, I have test before pull, ConfigUpdater shade from https://github.com/tchristofferson/Config-Updater

Can you include maven configuration for shading that?

2021-08-10 15:07 UTC, dhannyjsb commented
> 
> 
> > > When i build it and try to run it, I get a noClassDefFoundError for ConfigUpdater. Am I doing something wrong? Have you even tested this?
> > 
> > 
> > yes, I have test before pull, ConfigUpdater shade from https://github.com/tchristofferson/Config-Updater
> 
> Can you include maven configuration for shading that?



> 
> 
> > > When i build it and try to run it, I get a noClassDefFoundError for ConfigUpdater. Am I doing something wrong? Have you even tested this?
> > 
> > 
> > yes, I have test before pull, ConfigUpdater shade from https://github.com/tchristofferson/Config-Updater
> 
> Can you include maven configuration for shading that?

Okay, can you review my latest commit from pom.xml

2021-08-10 15:19 UTC, MagicCheese1 approved these changes
Everything looks good. Thanks for the pr

2021-08-10 15:19 UTC, merged